pip list
Package                      Version
---------------------------- ---------
aiohappyeyeballs             2.6.1
aiohttp                      3.12.6
aiosignal                    1.3.2
annotated-types              0.7.0
anyio                        4.9.0
async-timeout                4.0.3
attrs                        25.3.0
beautifulsoup4               4.13.4
bs4                          0.0.2
cachetools                   5.5.2
certifi                      2025.4.26
charset-normalizer           3.4.2
colorama                     0.4.6
dataclasses-json             0.6.3
exceptiongroup               1.3.0
filetype                     1.2.0
frozenlist                   1.6.0
google-ai-generativelanguage 0.6.18
google-api-core              2.24.2
google-api-python-client     2.170.0
google-auth                  2.40.2
google-auth-httplib2         0.2.0
google-generativeai          0.7.2
googleapis-common-protos     1.70.0
greenlet                     3.2.2
grpcio                       1.73.0rc1
grpcio-status                1.63.0rc1
h11                          0.16.0
httpcore                     1.0.9
httplib2                     0.22.0
httpx                        0.28.1
idna                         3.10
jsonpatch                    1.33
jsonpointer                  3.0.0
langchain                    0.3.25
langchain-core               0.3.63
langchain-google-genai       2.1.5
langchain-tavily             0.2.0
langchain-text-splitters     0.3.8
langsmith                    0.3.43
marshmallow                  3.26.1
multidict                    6.4.4
mypy                         1.16.0
mypy_extensions              1.1.0
orjson                       3.10.18
packaging                    24.2
pathspec                     0.12.1
pillow                       11.2.1
pip                          25.1
propcache                    0.3.1
proto-plus                   1.26.1
protobuf                     4.25.8
pyasn1                       0.6.1
pyasn1_modules               0.4.2
pydantic                     2.11.5
pydantic_core                2.33.2
pyparsing                    3.2.3
python-dotenv                1.1.0
PyYAML                       6.0.2
redis                        5.0.1
requests                     2.32.3
requests-toolbelt            1.0.0
rsa                          4.9.1
setuptools                   78.1.1
sniffio                      1.3.1
soupsieve                    2.7
SQLAlchemy                   2.0.41
tenacity                     9.1.2
tomli                        2.2.1
tqdm                         4.67.1
typing_extensions            4.13.2
typing-inspect               0.9.0
typing-inspection            0.4.1
uritemplate                  4.1.1
urllib3                      2.4.0
wheel                        0.45.1
yarl                         1.20.0
zstandard                    0.23.0